project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: intro.qmd
        text: "Primeiros Passos"
      - href: pressupostos.qmd
        text: "Análise de Pressupostos"
      - href: testes.qmd
        text: "Testes Estatísticos"
      - href: post.qmd
        text: "Testes Post-Hoc"
      - text: "Mais"
        menu:
          - href: ggplot.qmd
            text: "O Básico do ggplot2"
          - href: shiny.qmd
            text: "O Básico do Shiny"
          - href: pacs.qmd
            text: "Sugestões de Pacotes"

format:
  html:
    theme: lux
    css: 
      - styles.css
      - https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css
    toc: true
    highlight: pygments
    theme-dark: false

editor: visual